// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package postgresdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    organizer_id,
    title,
    description,
    location,
    image_url,
    start_time,
    end_time,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id,
    organizer_id,
    title,
    description,
    location,
    image_url,
    start_time,
    end_time,
    status,
    created_at,
    updated_at
`

type CreateEventParams struct {
	OrganizerID int32
	Title       string
	Description pgtype.Text
	Location    string
	ImageUrl    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
}

type CreateEventRow struct {
	ID          int32
	OrganizerID int32
	Title       string
	Description pgtype.Text
	Location    string
	ImageUrl    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrganizerID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.ImageUrl,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventByAdmin = `-- name: DeleteEventByAdmin :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEventByAdmin(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEventByAdmin, id)
	return err
}

const deleteEventByOrganizer = `-- name: DeleteEventByOrganizer :exec
DELETE FROM events
WHERE id = $1
  AND organizer_id = $2
`

type DeleteEventByOrganizerParams struct {
	ID          int32
	OrganizerID int32
}

func (q *Queries) DeleteEventByOrganizer(ctx context.Context, arg DeleteEventByOrganizerParams) error {
	_, err := q.db.Exec(ctx, deleteEventByOrganizer, arg.ID, arg.OrganizerID)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    id,
    organizer_id,
    title,
    description,
    location,
    image_url,
    start_time,
    end_time,
    status,
    created_at,
    updated_at
FROM events
WHERE id = $1
`

type GetEventByIDRow struct {
	ID          int32
	OrganizerID int32
	Title       string
	Description pgtype.Text
	Location    string
	ImageUrl    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetEventByID(ctx context.Context, id int32) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.ImageUrl,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventsByOrganizer = `-- name: GetEventsByOrganizer :many
SELECT
    id,
    organizer_id,
    title,
    description,
    location,
    image_url,
    start_time,
    end_time,
    status,
    created_at,
    updated_at
FROM events
WHERE organizer_id = $1
ORDER BY created_at DESC
`

type GetEventsByOrganizerRow struct {
	ID          int32
	OrganizerID int32
	Title       string
	Description pgtype.Text
	Location    string
	ImageUrl    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetEventsByOrganizer(ctx context.Context, organizerID int32) ([]GetEventsByOrganizerRow, error) {
	rows, err := q.db.Query(ctx, getEventsByOrganizer, organizerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByOrganizerRow
	for rows.Next() {
		var i GetEventsByOrganizerRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.ImageUrl,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishedEvents = `-- name: GetPublishedEvents :many
SELECT
    id,
    organizer_id,
    title,
    description,
    location,
    image_url,
    start_time,
    end_time,
    status,
    created_at,
    updated_at
FROM events
WHERE status = 'published'
  AND start_time > NOW()
ORDER BY start_time ASC
`

type GetPublishedEventsRow struct {
	ID          int32
	OrganizerID int32
	Title       string
	Description pgtype.Text
	Location    string
	ImageUrl    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetPublishedEvents(ctx context.Context) ([]GetPublishedEventsRow, error) {
	rows, err := q.db.Query(ctx, getPublishedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublishedEventsRow
	for rows.Next() {
		var i GetPublishedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.ImageUrl,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventByAdmin = `-- name: UpdateEventByAdmin :one
UPDATE events
SET
    title = $2,
    description = $3,
    location = $4,
    image_url = $5,
    start_time = $6,
    end_time = $7,
    status = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    organizer_id,
    title,
    status,
    updated_at
`

type UpdateEventByAdminParams struct {
	ID          int32
	Title       string
	Description pgtype.Text
	Location    string
	ImageUrl    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
}

type UpdateEventByAdminRow struct {
	ID          int32
	OrganizerID int32
	Title       string
	Status      string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateEventByAdmin(ctx context.Context, arg UpdateEventByAdminParams) (UpdateEventByAdminRow, error) {
	row := q.db.QueryRow(ctx, updateEventByAdmin,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.ImageUrl,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i UpdateEventByAdminRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventByOrganizer = `-- name: UpdateEventByOrganizer :one
UPDATE events
SET
    title = $3,
    description = $4,
    location = $5,
    image_url = $6,
    start_time = $7,
    end_time = $8,
    status = $9,
    updated_at = NOW()
WHERE id = $1
  AND organizer_id = $2
RETURNING
    id,
    organizer_id,
    title,
    status,
    updated_at
`

type UpdateEventByOrganizerParams struct {
	ID          int32
	OrganizerID int32
	Title       string
	Description pgtype.Text
	Location    string
	ImageUrl    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
}

type UpdateEventByOrganizerRow struct {
	ID          int32
	OrganizerID int32
	Title       string
	Status      string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateEventByOrganizer(ctx context.Context, arg UpdateEventByOrganizerParams) (UpdateEventByOrganizerRow, error) {
	row := q.db.QueryRow(ctx, updateEventByOrganizer,
		arg.ID,
		arg.OrganizerID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.ImageUrl,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i UpdateEventByOrganizerRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Title,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
