// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          int32
	OrganizerID int32
	Title       string
	Description pgtype.Text
	ImageUrl    pgtype.Text
	Location    string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
