// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_gen

import (
	"database/sql"

	"github.com/google/uuid"
)

type Booking struct {
	ID        uuid.UUID
	EventID   string
	UserID    string
	CreatedAt sql.NullTime
}

type Seat struct {
	ID         uuid.UUID
	EventID    string
	RowID      string
	SeatNumber int32
	Status     string
}
