// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seats.sql

package sqlc_gen

import (
	"context"

	"github.com/google/uuid"
)

const insertMultipleSeats = `-- name: InsertMultipleSeats :exec
INSERT INTO seats (id, event_id, row_id, seat_number, status)
VALUES 
($1, $2, $3, $4, $5)
ON CONFLICT (event_id, row_id, seat_number) DO NOTHING
`

type InsertMultipleSeatsParams struct {
	ID         uuid.UUID
	EventID    string
	RowID      string
	SeatNumber int32
	Status     string
}

// sqlc doesn’t support variadic insert, so you call this in a loop
func (q *Queries) InsertMultipleSeats(ctx context.Context, arg InsertMultipleSeatsParams) error {
	_, err := q.db.ExecContext(ctx, insertMultipleSeats,
		arg.ID,
		arg.EventID,
		arg.RowID,
		arg.SeatNumber,
		arg.Status,
	)
	return err
}

const insertSeat = `-- name: InsertSeat :one
INSERT INTO seats (id, event_id, row_id, seat_number, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (event_id, row_id, seat_number) DO NOTHING
RETURNING id, event_id, row_id, seat_number, status
`

type InsertSeatParams struct {
	ID         uuid.UUID
	EventID    string
	RowID      string
	SeatNumber int32
	Status     string
}

func (q *Queries) InsertSeat(ctx context.Context, arg InsertSeatParams) (Seat, error) {
	row := q.db.QueryRowContext(ctx, insertSeat,
		arg.ID,
		arg.EventID,
		arg.RowID,
		arg.SeatNumber,
		arg.Status,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.RowID,
		&i.SeatNumber,
		&i.Status,
	)
	return i, err
}
